services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfilebackend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfilefrontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfileadmin
    ports:
      - "4173:4173"
    depends_on:
      - backend
